config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  devise_for :models
  resources :proveedors
  resources :ficha_docs do
    collection do
      get 'search_bussine'
      get 'table_search'
    end
  end
  root :to => 'ficha_medicas#index'
  resources :areas
  resources :origens
  resources :etnias
  resources :estado_civils
  resources :nivel_academicos
  resources :sexos
  resources :stock_medicas
  resources :medicamentos
  resources :ficha_medicas do
    resources :diagnosticos 
  end
  get 'diagnosticos/consultas' => 'diagnosticos#consultas', :as => :consultas
  resources :diagnosticos do
    resources :ficha_docs do
      resources :stock_medicas
    end
  end
  resources :categoris
  resources :puesto_saluds do 
    collection do get "getInfo"
    end
  end    
  # devise_for :models
  # devise_for :users
  # resources :layouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ficha_medica.rb
class FichaMedica < ApplicationRecord
	belongs_to :categori
	belongs_to :puesto_salud
	belongs_to :sexo
	belongs_to :estado_civil
	belongs_to :origen
	belongs_to :nivel_academico
	belongs_to :area
	has_many :diagnosticos
	
	validates :categori_id, :presence => {:message => "seleccione un Tipo de Ficha"}
	validates :puesto_salud_id, :presence => {:message => "seleccione un Puesto de Salud"}
	validates :sexo_id, :presence => {:message => "seleccione un Sexo"}
	validates :origen_id, :presence => {:message => "seleccione una Etnia"}
	validates :nivel_academico_id, :presence => {:message => "seleccione Nivel Academico"}
	validates :area_id, :presence => {:message => "seleccione un Area"}
	
	validates :numero, uniqueness: { message: "El Numero ya Existe" }, 
				:numericality => {:numero => 0, :message => "debe ser un numero positivo"}
	validates :ci, uniqueness: { message: "El Numero de Cedula ya Existe" }, on: :create
	validates :especialidad, :nombre, :apellido, :edad,:fechaNacimiento, :lugarNacimiento, :nacionalidad,:telefono, :nCasa, :email, :direccionActual, :departamentoActual, :distritoActual, presence: true
end

app/controllers/ficha_medicas_controller.rb
class FichaMedicasController < ApplicationController
  before_action :set_ficha_medica, only: [:show, :pdf, :edit, :update, :destroy]

  # GET /ficha_medicas
  # GET /ficha_medicas.json
  def index
    @ficha_medicas = FichaMedica.all
    @categoris = Categori.all
    @puesto_saluds = PuestoSalud.all
  end

  # GET /ficha_medicas/1
  # GET /ficha_medicas/1.json
  def show
    
  end

  def pdf
    @ficha_medica = FichaMedica.find(params[:id])
     respond_to do |format|
      format.html
        format.pdf do
          pdf = FichaPdf.new
          send_data pdf.render, filename: 'ficha_medica_#{@FichaMedica.ficha_medica_nombre}.pdf', 
                                type:'application/pdf', 
                                disposition: "inline"
        end
      end
  end

  def consul
    FichaMedica.where(id: params[:ficha_medica_ids]).update_all(consulta: true)
    redirect_to ficha_medicas_url
  end
  
  # GET /ficha_medicas/new
  def new
    @ficha_medica = FichaMedica.new
    @categoris = Categori.all
    @puesto_salud = PuestoSalud.all
    @sexos = Sexo.all
    @nivel_academicos = NivelAcademico.all
    @origens = Origen.all
    @estado_civils = EstadoCivil.all
    @areas = Area.all
  end

  # GET /ficha_medicas/1/edit
  def edit
    @categoris = Categori.all
    @puesto_salud = PuestoSalud.all
    @sexos = Sexo.all
    @nivel_academicos = NivelAcademico.all
    @origens = Origen.all
    @estado_civils = EstadoCivil.all
    @areas = Area.all
  end

  # POST /ficha_medicas
  # POST /ficha_medicas.json
  def create
    @ficha_medica = FichaMedica.new(ficha_medica_params)

    respond_to do |format|
      if @ficha_medica.save
        format.html { redirect_to ficha_medicas_url, notice: 'Ficha medica was successfully created.' }
        format.json { render :index, status: :created, location: @ficha_medica }
      else
        format.html { render :new }
        format.json { render json: @ficha_medica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ficha_medicas/1
  # PATCH/PUT /ficha_medicas/1.json
  def update
    respond_to do |format|
      if @ficha_medica.update(ficha_medica_params)
        format.html { redirect_to @ficha_medica, notice: 'Ficha medica was successfully updated.' }
        format.json { render :index, status: :ok, location: @ficha_medica }
      else
        format.html { render :edit }
        format.json { render json: @ficha_medica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ficha_medicas/1
  # DELETE /ficha_medicas/1.json
  def destroy
    @ficha_medica.destroy
    respond_to do |format|
      format.html { redirect_to ficha_medicas_url, notice: 'Ficha medica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha_medica
      @ficha_medica = FichaMedica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_medica_params
      params.require(:ficha_medica).permit(:categori_id,:puesto_salud_id,:diagnostico_id,:sexo_id,:origen_id,:estado_civil_id,:nivel_academico_id,:area_id,:numero, :especialidad, :nombre, :apellido, :edad, :ci,:fechaNacimiento, :lugarNacimiento, :nacionalidad,:telefono, :nCasa, :email, :direccionActual, :departamentoActual, :distritoActual, :consulta)
    end
end

app/views/ficha_medicas/_form.html.erb
<%= form_with(model: ficha_medica, local: true) do |form| %>
  <% if ficha_medica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ficha_medica.errors.count, "error") %></h2>

      <ul>
      <% ficha_medica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<div class="container">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <center><h2>Ficha Clinica</h2></center>
      <div class="row">
        <div class="col-xs-2">
          <%= form.label :numero, 'Numero de Ficha' %>
          <%= form.number_field :numero, id: :ficha_medica_numero, class: 'form-control'%>
        </div>

        <div class="col-xs-3">
          <label>Tipo de Ficha</label>
          <%= form.collection_select(:categori_id, Categori.all, :id, :tipo, {include_blank: 'Tipo de Ficha' }, {:class=>'form-control'}) %>
        </div>
      </div>

      <hr>
        <center><h4>Datos del Establecimiento</h4></center>
      <hr>
        <div class="row">
          <div class="col-sm-3">
            <%= form.label :especialidad %>
            <%= form.text_field :especialidad, id: :ficha_medica_especialidad, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <div class="col-md-6">
              <label>Puesto de Salud</label>
              <%= form.collection_select(:puesto_salud_id, PuestoSalud.all, :id, :nombre, {include_blank: 'Puesto de Salud' }, {:class=>'form-control', :id=>'select_puesto_salud'}) %>
            </div>
                <div class="col-md-6">
                    <div class="form-group">
                    <label for="disabledTextInput">Localidad</label>
                    <input type="text" id="disabledTextInput" class="form-control" disabled= "disabled" >
                  </div>
                </div>
          </div>
          <div class="form-group">
                <div class="col-md-6">
                    <label>Distrito</label>
                    <input type="text" id="tbDistrito" class="form-control" disabled= "disabled">
                </div>
                <div class="col-md-6">
                    <label>Region Sanitaria</label>
                    <input type="text" id="tbRegion" class="form-control" disabled= "disabled">
                </div>
        </div>
      </div>



      <div class="row">
        <hr>
        <center><h4>Datos de Paciente</h4></center>
        <hr>
          <div class="col-lg-3">
              <%= form.label :ci , 'Numero de Documento'%>
              <%= form.text_field :ci, id: :ficha_medica_ci, class: "form-control" %>
          </div>
          <div class="col-lg-8">
          </div>
      </div>
      <div class="row">
                <div class="col-lg-6">
                  <%= form.label :nombre,'Nombre(s)' %>
                  <%= form.text_field :nombre, id: :ficha_medica_nombre, class: "form-control"  %>
                  
                </div>
                <div class="col-lg-6">
                  <%= form.label :apellido, 'Apellido(s)' %>
                  <%= form.text_field :apellido, id: :ficha_medica_apellido, class: "form-control" %>
                </div>
                
                <div class="col-md-6">
                  <%= form.label :fechaNacimiento,'Fecha de Nacimiento' %>
                  <%= form.date_field :fechaNacimiento, id: :ficha_medica_fehcaNacimiento, class: "form-control" %>
                </div>

                <div class="col-lg-4">
                  <%= form.label :edad %>
                  <%= form.number_field :edad, id: :ficha_medica_edad, class: "form-control" %>
                </div>

                <div class="col-md-6">
                  <%= form.label :lugarNacimiento, "Lugar de Nacimiento" %>
                  <%= form.text_field :lugarNacimiento, id: :ficha_medica_lugarNacimiento, class: "form-control" %>
                </div>

                <div class="col-xs-3">
                  <label>Sexo</label>
                  <%= form.collection_select(:sexo_id, Sexo.all, :id, :sexo, {include_blank: 'Seleccione Sexo' }, {:class=>'form-control'}) %>
                </div>


                <div class="col-md-6">
                  <%= form.label :nacionalidad %>
                  <%= form.text_field :nacionalidad, id: :ficha_medica_nacionalidad, class: "form-control" %>
                </div>

                <div class="col-xs-3">
                  <label>Etnia</label>
                  <%= form.collection_select(:origen_id, Origen.all, :id, :etnia, {include_blank: 'Tipo de Etnia'}, {:class=>'form-control'}) %>
                </div>
        
                <div class="col-xs-3">
                  <label>Estado Civil</label>
                  <%= form.collection_select(:estado_civil_id, EstadoCivil.all, :id, :estadoCivil, {include_blank: 'Seleccione Estado Civil'}, {:class=>'form-control'}) %>
                </div>

                 <div class="col-md-6">
                  <%= form.label :direccionActual, 'Dirección' %>
                  <%= form.text_field :direccionActual, id: :ficha_medica_direccionActual, class: "form-control" %>
                </div>

                <div class="col-md-6">
                  <%= form.label :departamentoActual, 'Departamento' %>
                  <%= form.text_field :departamentoActual, id: :ficha_medica_departamentoActual, class: "form-control" %>
                </div>

                <div class="col-md-6">
                  <%= form.label :distritoActual ,'Distrito'%>
                  <%= form.text_field :distritoActual, id: :ficha_medica_distritoActual, class: "form-control" %>
                </div>

                <div class="col-xs-3">
                  <label>Àrea</label>
                  <%= form.collection_select(:area_id, Area.all, :id, :area, {include_blank: 'Seleccione un Área' }, {:class=>'form-control'}) %>
                </div>

                <div class="col-md-6">
                  <%= form.label :telefono %>
                  <%= form.number_field :telefono, id: :ficha_medica_telefono, class: "form-control" %>
                </div>

                <div class="col-md-3">
                  <%= form.label :nCasa , 'Numero de Casa'%>
                  <%= form.number_field :nCasa, id: :ficha_medica_nCasa, class: "form-control" %>
                </div>

                <div class="col-md-6">
                  <%= form.label :email %>
                  <%= form.text_field :email, id: :ficha_medica_email , class: "form-control"%>
                </div>

                <div class="col-xs-4">
                  <label>Nivel Academico</label>
                  <%= form.collection_select(:nivel_academico_id, NivelAcademico.all, :id, :nivelAcdemico, {include_blank: 'Seleccione Nivel Academico' }, {:class=>'form-control'}) %>
                </div>

                <div class="row">
                  <div class="col-md-8"></div>
                  <div class="col-md-4">
                    <div class="actions"><BR>
                      <%= form.submit 'Guardar', class: "btn btn-success" %>
                      <%= link_to 'Atras', ficha_medicas_path , class: "btn btn-info"%>

                    </div>
                  </div>
                </div>
        </div>
      </div>
    </div>
  <div class="col-md-1"></div>
</div>


<% end %>
<script type="text/javascript">
  
    $("#select_puesto_salud" ).change(function() {
      var id = $('#select_puesto_salud').val();

      $.ajax({
              type:'GET', 
              url: '/puesto_saluds/getInfo',
              data: {"id": id},

              success: function(data) {
                console.log(data.nombre);
                $('#disabledTextInput').val(data.localidad);
                $('#tbDistrito').val(data.distrito);
                $('#tbRegion').val(data.regionSanitaria);
                  console.log(data);
                  
              },
              error: function(data) {
                    alert('error');
              }

               //data: $.param({ pagetime: {pagename: "whatever", start: 7, end: 21 }})
          });

      });
</script>

app/views/ficha_medicas/consultas.html.erb
<% @ficha_medica.diagnosticos.each do |consultas| %>

<%end%>

app/views/ficha_medicas/edit.html.erb
<h1>Editing Ficha Medica</h1>

<%= render 'form', ficha_medica: @ficha_medica %>

<%= link_to 'Show', @ficha_medica %> |
<%= link_to 'Back', ficha_medicas_path %>

app/views/ficha_medicas/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Fichas Medicas</h1>
  <table id="ficha_table" class="table table-hover">
        <thead>
          <tr>
            <th>Nº de Ficha</th> 
            <th>C.I.Nº</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo de Ficha</th>
            <th>Puesto</th>
            <th>Ver</th>
             <th>Editar</th>
          </tr>
        </thead>

        <tbody>
          <% @ficha_medicas.each do |ficha_medica| %>
            <tr>
              <td><%= ficha_medica.numero %></td>
              <td><%= ficha_medica.ci %></td>
              <td><%= ficha_medica.nombre %></td>
              <td><%= ficha_medica.apellido %></td>
              <td><%= ficha_medica.categori.tipo %></td>
              <td><%= ficha_medica.puesto_salud.nombre %></td>
               
              <td><%= link_to '', ficha_medica , class: "btn btn-primary btn-sm fa fa-eye" %></td>
              <td><%= link_to '', edit_ficha_medica_path(ficha_medica), class: "btn btn-default btn-sm fa fa-pencil" %></td>
              
            </tr>
             <% end %>
         
        </tbody>
      </table>
   


  <script type="text/javascript">
    //

    $(document).ready(function() {
    $('#ficha_table').DataTable( {
        responsive: true,
        "bProcessing": true,
        //"sPaginationType": "full_numbers",
        "paging": true,
        "iDisplayLength": 10,
        "bPaginate": true,
        "bSort": true,
        "oLanguage": {
            "oPaginate": {
                "sPrevious": "←",
                "sNext": "→",
                "sLast": "»",
                "sFirst": "«"
            },
            "sProcessing": "Procesando...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "No se encontraron resultados",
            "sEmptyTable": "Ningún dato disponible en esta tabla",
            "sInfo": "Mostrando de _START_ al _END_ de _TOTAL_ registros",
            //"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando del 0 al 0 de 0 registros",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix": "",
            "sSearch": "Buscar: ",
            "sUrl": "",
            "sInfoThousands": ".",
            "sLoadingRecords": "Cargando...",
            "oAria": {
                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
    } );
    } );

    $("#check_box" ).change(function() {
      alert.log(entroo);
    } );
    
  </script>

app/views/ficha_medicas/new.html.erb
<%= render 'form', ficha_medica: @ficha_medica %>

app/views/ficha_medicas/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
      <div class="col-sm-6">
        <strong>Ficha Numero:</strong>
         <%= @ficha_medica.numero %>
      </div>

      <div class="col-sm-6">
        <strong>C.I.Nº:</strong>
         <%= @ficha_medica.ci %>
      </div>

      <div class="col-sm-6">
        <strong>Nombre:</strong>
        <%= @ficha_medica.nombre %>
      </div>

      <div class="col-sm-6">
        <strong>Apellido:</strong>
        <%= @ficha_medica.apellido %>
      </div>

      <div class="col-sm-6">
        <strong>Edad:</strong>
        <%= @ficha_medica.edad %>
      </div>

</div><BR>
      <%= form_for([@ficha_medica, @ficha_medica.diagnosticos.build]) do |f| %>
  <div class="row">
          <div class="col-sm-3">
            <%= f.label :fecha , "Fecha" %>
            <%= f.date_field :fecha, id: :diagnostico_fecha, class: "form-control", required: true, :validate => true, :order => [:day, :month, :year]%>
          </div>
    
  </div>
         
  <div class="row">
          <div class="col-sm-2">
            <%= f.label :axilaRectal, "Axila Rectal" %>
            <%= f.text_field :axilaRectal, id: :diagnostico_axilaRectal , class: "form-control"  %>
          </div>

          <div class="col-sm-2">
            <%= f.label :presionArterial, "Presion Arterial" %>
            <%= f.text_field :presionArterial, id: :diagnostico_presionArterial , class: "form-control"  %>
          </div>

          <div class="col-sm-2">
            <%= f.label :pulso, "Pulso" %>
            <%= f.text_field :pulso, id: :diagnostico_pulso, class: "form-control"  %>
          </div>

          <div class="col-sm-3">
            <%= f.label :freCardiaca, "Frecuencia Cardiaca" %>
            <%= f.text_field :freCardiaca, id: :diagnostico_freCardiaca, class: "form-control"  %>
          </div>

          <div class="col-sm-3">
            <%= f.label :freRespi, "Frecuencia Respiratoria" %>
            <%= f.text_field :freRespi, id: :diagnostico_freRespi, class: "form-control"  %>
          </div>
</div>
<div class="row">
          <div class="col-sm-2">
            <%= f.label :peso, "Peso" %>
            <%= f.text_field :peso, id: :diagnostico_peso, class: "form-control"  %>
          </div>

          <div class="col-sm-2">
            <%= f.label :talla, "Talla" %>
            <%= f.text_field :talla, id: :diagnostico_talla, class: "form-control"  %>
          </div>
          <div class="col-sm-3">
            <%= f.label :perimeCefalico, "Perimetro Cefalico" %>
            <%= f.text_field :perimeCefalico, id: :diagnostico_perimeCefalico, class: "form-control"  %>
          </div>
          <div class="col-sm-3">
            <%= f.label :masaCorpo, "Masa Corporal" %>
            <%= f.text_field :masaCorpo, id: :diagnostico_masaCorpo, class: "form-control"  %>
          </div>
</div>
<div class="row">

          <div class="col-sm-3">
            <%= f.label :circuAbdomi, "Circunferencia Abdominal" %>
            <%= f.text_field :circuAbdomi, id: :diagnostico_circuAbdomi, class: "form-control"  %>
          </div>
          
          <div class="col-sm-3">
            <%= f.label :estadNutricional, "Estado Nutricional" %>
            <%= f.text_field :estadNutricional, id: :diagnostico_estadNutricional, class: "form-control"  %>
          </div>

          <div class="col-sm-3">
            <%= f.label :alimentacion, "Alimentación" %>
            <%= f.text_field :alimentacion, id: :diagnostico_alimentacion, class: "form-control"  %>
          </div>

          <div class="col-sm-3">
            <%= f.label :desarrolloMadura, "Desarrollo Madurativo" %>
            <%= f.text_field :desarrolloMadura, id: :diagnostico_desarrolloMadura, class: "form-control"  %>
          </div>
</div>
<div class="row">
          <div class="col-sm-2">
            <%= f.label :tanner, "Tanner" %>
            <%= f.text_field :tanner, id: :diagnostico_tanner, class: "form-control"  %>
          </div>

          <div class="col-sm-3">
            <%= f.label :vacucacionVigente, "Vacunacion Vigente" %>
            <%= f.text_field :vacucacionVigente, id: :diagnostico_vacucacionVigente, class: "form-control"  %>
          </div>

          <div class="col-sm-4">
            <%= f.label :areaTecEspecialidades, "Area Tecnica Especialidades" %>
            <%= f.text_field :areaTecEspecialidades, id: :diagnostico_areaTecEspecialidades, class: "form-control"  %>
          </div>

          <div class="col-sm-2">
            <%= f.label :nuevo, "Nuevo" %>
            <%= f.text_field :nuevo, id: :diagnostico_nuevo, class: "form-control"  %>
          </div>
          <div>
            <%= f.label :consultar %>
            <%= f.check_box :consultar, id: :diagnostico_consultar, required: true %>
          </div>
</div><BR>
<div class="row">
  <DIV CLASS="col-sm-10"></div>
  <DIV CLASS="col-sm-2">
              <%= f.submit 'Guardar', class: "btn btn-success" %>
  </DIV>
</div>
    <%end%>
   