config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  devise_for :models
  resources :proveedors
  resources :ficha_docs do
    collection do
      get 'search_bussine'
      get 'table_search'
    end
  end
  root :to => 'ficha_medicas#index'
  resources :areas
  resources :origens
  resources :etnias
  resources :estado_civils
  resources :nivel_academicos
  resources :sexos
  resources :stock_medicas
  resources :medicamentos
  resources :ficha_medicas do
    resources :diagnosticos 
  end
  get 'diagnosticos/consultas' => 'diagnosticos#consultas', :as => :consultas
  resources :diagnosticos do
    resources :ficha_docs do
      resources :stock_medicas
    end
  end
  resources :categoris
  resources :puesto_saluds do 
    collection do get "getInfo"
    end
  end    
  # devise_for :models
  # devise_for :users
  # resources :layouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :ficha_medicas
end

app/models/categori.rb
class Categori < ApplicationRecord
	has_many :ficha_medicas
end

app/models/detalle.rb
class Detalle < ApplicationRecord
	belongs_to :medicamento
	after_save :sumar_medicamentos
	def sumar_medicamentos
	    self.medicamento.cantidad += self.cantidad
	    self.medicamento.save
	 end
end

app/models/diagnostico.rb
class Diagnostico < ApplicationRecord
	belongs_to :ficha_medica
	has_many :ficha_docs
	has_many :stock_medicas
	accepts_nested_attributes_for :stock_medicas,  allow_destroy: true
	accepts_nested_attributes_for :ficha_docs
end

app/models/estado_civil.rb
class EstadoCivil < ApplicationRecord
	has_many :ficha_medicas
end

app/models/ficha_doc.rb
class FichaDoc < ApplicationRecord
	belongs_to :diagnostico
end

app/models/ficha_medica.rb
class FichaMedica < ApplicationRecord
	belongs_to :categori
	belongs_to :puesto_salud
	belongs_to :sexo
	belongs_to :estado_civil
	belongs_to :origen
	belongs_to :nivel_academico
	belongs_to :area
	has_many :diagnosticos
	
	validates :categori_id, :presence => {:message => "seleccione un Tipo de Ficha"}
	validates :puesto_salud_id, :presence => {:message => "seleccione un Puesto de Salud"}
	validates :sexo_id, :presence => {:message => "seleccione un Sexo"}
	validates :origen_id, :presence => {:message => "seleccione una Etnia"}
	validates :nivel_academico_id, :presence => {:message => "seleccione Nivel Academico"}
	validates :area_id, :presence => {:message => "seleccione un Area"}
	
	validates :numero, uniqueness: { message: "El Numero ya Existe" }, 
				:numericality => {:numero => 0, :message => "debe ser un numero positivo"}
	validates :ci, uniqueness: { message: "El Numero de Cedula ya Existe" }, on: :create
	validates :especialidad, :nombre, :apellido, :edad,:fechaNacimiento, :lugarNacimiento, :nacionalidad,:telefono, :nCasa, :email, :direccionActual, :departamentoActual, :distritoActual, presence: true
end

app/models/medicamento.rb
class Medicamento < ApplicationRecord
	validates :nombreMedi, uniqueness: { message: "El nombre del Medicamento ya Existe" }, on: :create	
	has_many :stock_medicas
	has_many :detalles
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/nivel_academico.rb
class NivelAcademico < ApplicationRecord
	has_many :ficha_medicas
end

app/models/origen.rb
class Origen < ApplicationRecord
	has_many :ficha_medicas
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
	has_many :detalles
	accepts_nested_attributes_for :detalles,  allow_destroy: true
end

app/models/puesto_salud.rb
class PuestoSalud < ApplicationRecord
	has_many :ficha_medicas
end

app/models/sexo.rb
class Sexo < ApplicationRecord
	has_many :ficha_medicas
end

app/models/stock_medica.rb
class StockMedica < ApplicationRecord
	belongs_to :diagnostico
	belongs_to :medicamento 
	after_save :descontar_medicamentos
	 # after_save :stock_negativo
	
	  # Este es un metodo que se disparara automaticamente despues que se guarde una compra
	  # self.bidon llama a la relacion belongs_to que esta arriba y le descuenta la cantidad comprada este es un campo de la tabla compra.
	  # luego se guarda el objeto relacionado

	  def descontar_medicamentos
	     	self.medicamento.cantidad -= self.cantidad
	     	self.medicamento.save
	   end
	  # controla que haya stock suficiente
	   # def stock_negativo
	   #   errors.add(:stock_medica_cantidad, "supera el stock exixtente") if Medicamento.find(medicamento_id).cantidad < stock_medica_cantidad
	   # end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view_consulta.rb
class ViewConsulta < ApplicationRecord
end

app/controllers/ficha_docs_controller.rb
class FichaDocsController < ApplicationController
  before_action :set_ficha_doc, only: [:show, :edit, :update, :destroy]

  # GET /ficha_docs
  # GET /ficha_docs.json
  def index
    @ficha_docs = FichaDoc.all
  end

  # GET /ficha_docs/1
  # GET /ficha_docs/1.json
  def show
    @diagnosticos = Diagnostico.all
    @stock_medicas = StockMedica.where(diagnostico_id == ficha_doc.diagnostico_id)        
  end

  # GET /ficha_docs/new
  def new
    @ficha_doc = FichaDoc.new

  end

  # GET /ficha_docs/1/edit
  def edit
  end

  # POST /ficha_docs
  # POST /ficha_docs.json
  
  

  def create
  
  @ficha_doc = FichaDoc.new(ficha_doc_params)

    respond_to do |format|
      if @ficha_doc.save
        format.html { redirect_to @ficha_doc, notice: 'Creado ' }
        format.json { render :show, status: :created, location: @ficha_dos }
      else
        format.html { render :show }
        format.json { render json: @ficha_doc.errors, status: :unprocessable_entity }
      end
    end
  end


  # @ficha_medica = FichaMedica.find(params[:ficha_medica_id])
  # @diagnostico = @ficha_medica.diagnosticos.create(diagnostico_params)


  # PATCH/PUT /ficha_docs/1
  # PATCH/PUT /ficha_docs/1.json
  def update
    respond_to do |format|
      if @ficha_doc.update(ficha_doc_params)
        format.html { redirect_to @ficha_doc, notice: 'Ficha doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @ficha_doc }
      else
        format.html { render :edit }
        format.json { render json: @ficha_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ficha_docs/1
  # DELETE /ficha_docs/1.json
  def destroy
    @ficha_doc.destroy
    respond_to do |format|
      format.html { redirect_to ficha_docs_url, notice: 'Ficha doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha_doc
      @ficha_doc = FichaDoc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_doc_params
      params.require(:ficha_doc).permit(:diagnostico_id,:motivoConsul, :examenFisico, :otroDiagnos, :tratamiento)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/ficha_docs_helper.rb
module FichaDocsHelper
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
		end
		def link_to_add_fields(name, f, association)
		    new_object = f.object.send(association).klass.new
		    id = new_object.object_id
		    fields = f.fields_for(association, new_object, child_index: id) do |document|
		      render(association.to_s.singularize + "_fields", f: document)
		    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/ficha_docs/_form.html.erb
<%= form_with(model: ficha_doc, local: true) do |form| %>
  <% if ficha_doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ficha_doc.errors.count, "error") %> prohibited this ficha_doc from being saved:</h2>

      <ul>
      <% ficha_doc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :motivoConsul %>
    <%= form.text_area :motivoConsul, id: :ficha_doc_motivoConsul %>
  </div>

  <div class="field">
    <%= form.label :examenFisico %>
    <%= form.text_area :examenFisico, id: :ficha_doc_examenFisico %>
  </div>

  <div class="field">
    <%= form.label :otroDiagnos %>
    <%= form.text_area :otroDiagnos, id: :ficha_doc_otroDiagnos %>
  </div>

  <div class="field">
    <%= form.label :tratamiento %>
    <%= form.text_area :tratamiento, id: :ficha_doc_tratamiento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ficha_docs/edit.html.erb
<h1>Editing Ficha Doc</h1>

<%= render 'form', ficha_doc: @ficha_doc %>

<%= link_to 'Show', @ficha_doc %> |
<%= link_to 'Back', ficha_docs_path %>

app/views/ficha_docs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historial de Consultas</h1>

<table id="table" class="table table-hover">
  <thead>
    <tr>
      <th>Nombre </th>
      <th>Apellido</th>
      <th>Motivo Consulta</th>
      <th>Examenfisico</th>
      <th>Otrodiagnos</th>
      <th>Tratamiento</th>
    </tr>
  </thead>

  <tbody>
    <% @ficha_docs.each do |ficha_doc| %>
      <tr>
        <td><%= ficha_doc.diagnostico.ficha_medica.nombre %></td>
        <td><%= ficha_doc.diagnostico.ficha_medica.apellido %></td>
        <td><%= ficha_doc.motivoConsul %></td>
        <td><%= ficha_doc.examenFisico %></td>
        <td><%= ficha_doc.otroDiagnos %></td>
        <td><%= ficha_doc.tratamiento %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type="text/javascript">
  $(document).ready(function() {
    $('#table').DataTable( {
        responsive: true,
        "bProcessing": true,
        //"sPaginationType": "full_numbers",
        "paging": true,
        "iDisplayLength": 10,
        "bPaginate": true,
        "bSort": true,
        "oLanguage": {
            "oPaginate": {
                "sPrevious": "←",
                "sNext": "→",
                "sLast": "»",
                "sFirst": "«"
            },
            "sProcessing": "Procesando...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "No se encontraron resultados",
            "sEmptyTable": "Ningún dato disponible en esta tabla",
            "sInfo": "Mostrando de _START_ al _END_ de _TOTAL_ registros",
            //"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando del 0 al 0 de 0 registros",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix": "",
            "sSearch": "Buscar: ",
            "sUrl": "",
            "sInfoThousands": ".",
            "sLoadingRecords": "Cargando...",
            "oAria": {
                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
    } );
    } );
</script>

app/views/ficha_docs/new.html.erb
<h1>New Ficha Doc</h1>

<%= render 'form', ficha_doc: @ficha_doc %>

<%= link_to 'Back', ficha_docs_path %>

app/views/ficha_docs/show.html.erb
<p id="notice"><%= notice %></p>
<center><h2>Receta Medica</h2></center>
<div class="row">
  <div class="col-sm-6">
    <strong>Fecha:</strong>
    <%= @ficha_doc.diagnostico.fecha %>
  </div>

  <div class="col-sm-6">
    <strong>Nombre del Paciente:</strong>
    <%= @ficha_doc.diagnostico.ficha_medica.nombre %>
    <%= @ficha_doc.diagnostico.ficha_medica.apellido %>
  </div>

</div><br>

<div class="row">
       <table id="" class="table">
            <thead>
             <tr>
                <th>Fecha</th>
                <th>Nombre del medicamento</th>
                <th>Cantidad</th>
              </tr>
            </thead>
            <tbody>
              <% @stock_medicas.each do |p| %>
               <tr>
                <td><%= p.diagnostico.fecha %></td>
                <td><%= p.medicamento.nombreMedi %></td>
                <td><%= p.cantidad %></td>
                
               </tr>
              <% end %>
            </tbody>
        </table>
</div>