config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  devise_for :models
  resources :proveedors
  resources :ficha_docs do
    collection do
      get 'search_bussine'
      get 'table_search'
    end
  end
  root :to => 'ficha_medicas#index'
  resources :areas
  resources :origens
  resources :etnias
  resources :estado_civils
  resources :nivel_academicos
  resources :sexos
  resources :stock_medicas
  resources :medicamentos
  resources :ficha_medicas do
    resources :diagnosticos 
  end
  get 'diagnosticos/consultas' => 'diagnosticos#consultas', :as => :consultas
  resources :diagnosticos do
    resources :ficha_docs do
      resources :stock_medicas
    end
  end
  resources :categoris
  resources :puesto_saluds do 
    collection do get "getInfo"
    end
  end    
  # devise_for :models
  # devise_for :users
  # resources :layouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :ficha_medicas
end

app/models/categori.rb
class Categori < ApplicationRecord
	has_many :ficha_medicas
end

app/models/detalle.rb
class Detalle < ApplicationRecord
	belongs_to :medicamento
	after_save :sumar_medicamentos
	def sumar_medicamentos
	    self.medicamento.cantidad += self.cantidad
	    self.medicamento.save
	 end
end

app/models/diagnostico.rb
class Diagnostico < ApplicationRecord
	belongs_to :ficha_medica
	has_many :ficha_docs
	has_many :stock_medicas
	accepts_nested_attributes_for :stock_medicas,  allow_destroy: true
	accepts_nested_attributes_for :ficha_docs
end

app/models/estado_civil.rb
class EstadoCivil < ApplicationRecord
	has_many :ficha_medicas
end

app/models/ficha_doc.rb
class FichaDoc < ApplicationRecord
	belongs_to :diagnostico
end

app/models/ficha_medica.rb
class FichaMedica < ApplicationRecord
	belongs_to :categori
	belongs_to :puesto_salud
	belongs_to :sexo
	belongs_to :estado_civil
	belongs_to :origen
	belongs_to :nivel_academico
	belongs_to :area
	has_many :diagnosticos
	
	validates :categori_id, :presence => {:message => "seleccione un Tipo de Ficha"}
	validates :puesto_salud_id, :presence => {:message => "seleccione un Puesto de Salud"}
	validates :sexo_id, :presence => {:message => "seleccione un Sexo"}
	validates :origen_id, :presence => {:message => "seleccione una Etnia"}
	validates :nivel_academico_id, :presence => {:message => "seleccione Nivel Academico"}
	validates :area_id, :presence => {:message => "seleccione un Area"}
	
	validates :numero, uniqueness: { message: "El Numero ya Existe" }, 
				:numericality => {:numero => 0, :message => "debe ser un numero positivo"}
	validates :ci, uniqueness: { message: "El Numero de Cedula ya Existe" }, on: :create
	validates :especialidad, :nombre, :apellido, :edad,:fechaNacimiento, :lugarNacimiento, :nacionalidad,:telefono, :nCasa, :email, :direccionActual, :departamentoActual, :distritoActual, presence: true
end

app/models/medicamento.rb
class Medicamento < ApplicationRecord
	validates :nombreMedi, uniqueness: { message: "El nombre del Medicamento ya Existe" }, on: :create	
	has_many :stock_medicas
	has_many :detalles
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/nivel_academico.rb
class NivelAcademico < ApplicationRecord
	has_many :ficha_medicas
end

app/models/origen.rb
class Origen < ApplicationRecord
	has_many :ficha_medicas
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
	has_many :detalles
	accepts_nested_attributes_for :detalles,  allow_destroy: true
end

app/models/puesto_salud.rb
class PuestoSalud < ApplicationRecord
	has_many :ficha_medicas
end

app/models/sexo.rb
class Sexo < ApplicationRecord
	has_many :ficha_medicas
end

app/models/stock_medica.rb
class StockMedica < ApplicationRecord
	belongs_to :diagnostico
	belongs_to :medicamento 
	after_save :descontar_medicamentos
	 # after_save :stock_negativo
	
	  # Este es un metodo que se disparara automaticamente despues que se guarde una compra
	  # self.bidon llama a la relacion belongs_to que esta arriba y le descuenta la cantidad comprada este es un campo de la tabla compra.
	  # luego se guarda el objeto relacionado

	  def descontar_medicamentos
	     	self.medicamento.cantidad -= self.cantidad
	     	self.medicamento.save
	   end
	  # controla que haya stock suficiente
	   # def stock_negativo
	   #   errors.add(:stock_medica_cantidad, "supera el stock exixtente") if Medicamento.find(medicamento_id).cantidad < stock_medica_cantidad
	   # end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view_consulta.rb
class ViewConsulta < ApplicationRecord
end

app/controllers/medicamentos_controller.rb
class MedicamentosController < ApplicationController
  before_action :set_medicamento, only: [:show, :edit, :update, :destroy]

  # GET /medicamentos
  # GET /medicamentos.json
  def index
    @medicamentos = Medicamento.all
  end

  # GET /medicamentos/1
  # GET /medicamentos/1.json
  def show
  end
  
  # GET /medicamentos/new
  def new
    @medicamento = Medicamento.new
  end

  # GET /medicamentos/1/edit
  def edit
  end

  # POST /medicamentos
  # POST /medicamentos.json
  def create
    @medicamento = Medicamento.new(medicamento_params)

    respond_to do |format|
      if @medicamento.save
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully created.' }
        format.json { render :show, status: :created, location: @medicamento }
      else
        format.html { render :new }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicamentos/1
  # PATCH/PUT /medicamentos/1.json
  def update
    respond_to do |format|
      if @medicamento.update(medicamento_params)
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicamento }
      else
        format.html { render :edit }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicamentos/1
  # DELETE /medicamentos/1.json
  def destroy
    @medicamento.destroy
    respond_to do |format|
      format.html { redirect_to medicamentos_url, notice: 'Medicamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicamento
      @medicamento = Medicamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicamento_params
      params.require(:medicamento).permit(:fechaVencimiento, :nombreMedi, :descripcion, :cantidad)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/ficha_docs_helper.rb
module FichaDocsHelper
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
		end
		def link_to_add_fields(name, f, association)
		    new_object = f.object.send(association).klass.new
		    id = new_object.object_id
		    fields = f.fields_for(association, new_object, child_index: id) do |document|
		      render(association.to_s.singularize + "_fields", f: document)
		    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/medicamentos/_form.html.erb
<%= form_with(model: medicamento, local: true) do |form| %>
  <% if medicamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicamento.errors.count, "error") %> prohibited this medicamento from being saved:</h2>

      <ul>
      <% medicamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <h2>Nuevo Medicamento</h2>

    <div class="field">
      <%= form.label :fechaVencimiento, "Fecha de Vencimiento" %>
      <%= form.date_field :fechaVencimiento, id: :medicamento_fechaVencimiento, class: "form-control"  %>
    </div>
    <div class="field">
      <%= form.label :nombreMedi, "Nombre del Medicamento" %>
      <%= form.text_field :nombreMedi, id: :medicamento_nombreMedi, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :descripcion, "Descripción" %>
      <%= form.text_area :descripcion, id: :medicamento_descripcion, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :cantidad, "Cantidad" %>
      <%= form.number_field :cantidad, id: :medicamento_cantidad, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit 'Guardar', class: "btn btn-success" %>
      <%= link_to 'Atras', medicamentos_path, class: "btn btn-info" %>
    </div>
  <% end %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/medicamentos/edit.html.erb
<h1>Editar Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Show', @medicamento %> |
<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicamentos</h1>
<div class= "col-md-10"></div>
<!-- <div class="col-md-2">
<%= link_to '', new_medicamento_path , class: "btn btn-success fa fa-plus"%>
</div> -->
<table id="medi_tabla"  class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Cantidad</th>
      <th>Fecha de Vencimiento</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= medicamento.nombreMedi %></td>
        <td><%= medicamento.descripcion %></td>
        <td><span class="badge badge-pill badge-primary"><%= medicamento.cantidad %></span></td>
        <td><%= medicamento.fechaVencimiento %></td>
        <td><%= link_to 'Show', medicamento %></td>
        <td><%= link_to 'Edit', edit_medicamento_path(medicamento) %></td>
        <td><%= link_to 'Destroy', medicamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>
  </tbody>
</table>

 <script type="text/javascript">
    //

    $(document).ready(function() {
    $('#medi_tabla').DataTable( {
        responsive: true,
        "bProcessing": true,
        //"sPaginationType": "full_numbers",
        "paging": true,
        "iDisplayLength": 10,
        "bPaginate": true,
        "bSort": true,
        "oLanguage": {
            "oPaginate": {
                "sPrevious": "←",
                "sNext": "→",
                "sLast": "»",
                "sFirst": "«"
            },
            "sProcessing": "Procesando...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "No se encontraron resultados",
            "sEmptyTable": "Ningún dato disponible en esta tabla",
            "sInfo": "Mostrando de _START_ al _END_ de _TOTAL_ registros",
            //"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando del 0 al 0 de 0 registros",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix": "",
            "sSearch": "Buscar: ",
            "sUrl": "",
            "sInfoThousands": ".",
            "sLoadingRecords": "Cargando...",
            "oAria": {
                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
    } );
    } );
    
  </script>

app/views/medicamentos/new.html.erb
<%= render 'form', medicamento: @medicamento %>

app/views/medicamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @medicamento.nombreMedi %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @medicamento.descripcion %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @medicamento.cantidad %>
</p>

<%= link_to 'Edit', edit_medicamento_path(@medicamento) %> |
<%= link_to 'Back', medicamentos_path %>