config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  devise_for :models
  resources :proveedors
  resources :ficha_docs do
    collection do
      get 'search_bussine'
      get 'table_search'
    end
  end
  root :to => 'ficha_medicas#index'
  resources :areas
  resources :origens
  resources :etnias
  resources :estado_civils
  resources :nivel_academicos
  resources :sexos
  resources :stock_medicas
  resources :medicamentos
  resources :ficha_medicas do
    resources :diagnosticos 
  end
  get 'diagnosticos/consultas' => 'diagnosticos#consultas', :as => :consultas
  resources :diagnosticos do
    resources :ficha_docs do
      resources :stock_medicas
    end
  end
  resources :categoris
  resources :puesto_saluds do 
    collection do get "getInfo"
    end
  end    
  # devise_for :models
  # devise_for :users
  # resources :layouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :ficha_medicas
end

app/models/categori.rb
class Categori < ApplicationRecord
	has_many :ficha_medicas
end

app/models/detalle.rb
class Detalle < ApplicationRecord
	belongs_to :medicamento
	after_save :sumar_medicamentos
	def sumar_medicamentos
	    self.medicamento.cantidad += self.cantidad
	    self.medicamento.save
	 end
end

app/models/diagnostico.rb
class Diagnostico < ApplicationRecord
	belongs_to :ficha_medica
	has_many :ficha_docs
	has_many :stock_medicas
	accepts_nested_attributes_for :stock_medicas,  allow_destroy: true
	accepts_nested_attributes_for :ficha_docs
end

app/models/estado_civil.rb
class EstadoCivil < ApplicationRecord
	has_many :ficha_medicas
end

app/models/ficha_doc.rb
class FichaDoc < ApplicationRecord
	belongs_to :diagnostico
end

app/models/ficha_medica.rb
class FichaMedica < ApplicationRecord
	belongs_to :categori
	belongs_to :puesto_salud
	belongs_to :sexo
	belongs_to :estado_civil
	belongs_to :origen
	belongs_to :nivel_academico
	belongs_to :area
	has_many :diagnosticos
	
	validates :categori_id, :presence => {:message => "seleccione un Tipo de Ficha"}
	validates :puesto_salud_id, :presence => {:message => "seleccione un Puesto de Salud"}
	validates :sexo_id, :presence => {:message => "seleccione un Sexo"}
	validates :origen_id, :presence => {:message => "seleccione una Etnia"}
	validates :nivel_academico_id, :presence => {:message => "seleccione Nivel Academico"}
	validates :area_id, :presence => {:message => "seleccione un Area"}
	
	validates :numero, uniqueness: { message: "El Numero ya Existe" }, 
				:numericality => {:numero => 0, :message => "debe ser un numero positivo"}
	validates :ci, uniqueness: { message: "El Numero de Cedula ya Existe" }, on: :create
	validates :especialidad, :nombre, :apellido, :edad,:fechaNacimiento, :lugarNacimiento, :nacionalidad,:telefono, :nCasa, :email, :direccionActual, :departamentoActual, :distritoActual, presence: true
end

app/models/medicamento.rb
class Medicamento < ApplicationRecord
	validates :nombreMedi, uniqueness: { message: "El nombre del Medicamento ya Existe" }, on: :create	
	has_many :stock_medicas
	has_many :detalles
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/nivel_academico.rb
class NivelAcademico < ApplicationRecord
	has_many :ficha_medicas
end

app/models/origen.rb
class Origen < ApplicationRecord
	has_many :ficha_medicas
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
	has_many :detalles
	accepts_nested_attributes_for :detalles,  allow_destroy: true
end

app/models/puesto_salud.rb
class PuestoSalud < ApplicationRecord
	has_many :ficha_medicas
end

app/models/sexo.rb
class Sexo < ApplicationRecord
	has_many :ficha_medicas
end

app/models/stock_medica.rb
class StockMedica < ApplicationRecord
	belongs_to :diagnostico
	belongs_to :medicamento 
	after_save :descontar_medicamentos
	 # after_save :stock_negativo
	
	  # Este es un metodo que se disparara automaticamente despues que se guarde una compra
	  # self.bidon llama a la relacion belongs_to que esta arriba y le descuenta la cantidad comprada este es un campo de la tabla compra.
	  # luego se guarda el objeto relacionado

	  def descontar_medicamentos
	     	self.medicamento.cantidad -= self.cantidad
	     	self.medicamento.save
	   end
	  # controla que haya stock suficiente
	   # def stock_negativo
	   #   errors.add(:stock_medica_cantidad, "supera el stock exixtente") if Medicamento.find(medicamento_id).cantidad < stock_medica_cantidad
	   # end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view_consulta.rb
class ViewConsulta < ApplicationRecord
end

app/controllers/nivel_academicos_controller.rb
class NivelAcademicosController < ApplicationController
  before_action :set_nivel_academico, only: [:show, :edit, :update, :destroy]

  # GET /nivel_academicos
  # GET /nivel_academicos.json
  def index
    @nivel_academicos = NivelAcademico.all
  end

  # GET /nivel_academicos/1
  # GET /nivel_academicos/1.json
  def show
  end

  # GET /nivel_academicos/new
  def new
    @nivel_academico = NivelAcademico.new
  end

  # GET /nivel_academicos/1/edit
  def edit
  end

  # POST /nivel_academicos
  # POST /nivel_academicos.json
  def create
    @nivel_academico = NivelAcademico.new(nivel_academico_params)

    respond_to do |format|
      if @nivel_academico.save
        format.html { redirect_to @nivel_academico, notice: 'Nivel academico was successfully created.' }
        format.json { render :show, status: :created, location: @nivel_academico }
      else
        format.html { render :new }
        format.json { render json: @nivel_academico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nivel_academicos/1
  # PATCH/PUT /nivel_academicos/1.json
  def update
    respond_to do |format|
      if @nivel_academico.update(nivel_academico_params)
        format.html { redirect_to @nivel_academico, notice: 'Nivel academico was successfully updated.' }
        format.json { render :show, status: :ok, location: @nivel_academico }
      else
        format.html { render :edit }
        format.json { render json: @nivel_academico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nivel_academicos/1
  # DELETE /nivel_academicos/1.json
  def destroy
    @nivel_academico.destroy
    respond_to do |format|
      format.html { redirect_to nivel_academicos_url, notice: 'Nivel academico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nivel_academico
      @nivel_academico = NivelAcademico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nivel_academico_params
      params.require(:nivel_academico).permit(:nivelAcdemico)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/ficha_docs_helper.rb
module FichaDocsHelper
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
		end
		def link_to_add_fields(name, f, association)
		    new_object = f.object.send(association).klass.new
		    id = new_object.object_id
		    fields = f.fields_for(association, new_object, child_index: id) do |document|
		      render(association.to_s.singularize + "_fields", f: document)
		    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/nivel_academicos/_form.html.erb
<%= form_with(model: nivel_academico, local: true) do |form| %>
  <% if nivel_academico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nivel_academico.errors.count, "error") %> prohibited this nivel_academico from being saved:</h2>

      <ul>
      <% nivel_academico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nivelAcdemico %>
    <%= form.text_field :nivelAcdemico, id: :nivel_academico_nivelAcdemico %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nivel_academicos/edit.html.erb
<h1>Editing Nivel Academico</h1>

<%= render 'form', nivel_academico: @nivel_academico %>

<%= link_to 'Show', @nivel_academico %> |
<%= link_to 'Back', nivel_academicos_path %>

app/views/nivel_academicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nivel Academicos</h1>

<table>
  <thead>
    <tr>
      <th>Nivelacdemico</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nivel_academicos.each do |nivel_academico| %>
      <tr>
        <td><%= nivel_academico.nivelAcdemico %></td>
        <td><%= link_to 'Show', nivel_academico %></td>
        <td><%= link_to 'Edit', edit_nivel_academico_path(nivel_academico) %></td>
        <td><%= link_to 'Destroy', nivel_academico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nivel Academico', new_nivel_academico_path %>

app/views/nivel_academicos/new.html.erb
<h1>New Nivel Academico</h1>

<%= render 'form', nivel_academico: @nivel_academico %>

<%= link_to 'Back', nivel_academicos_path %>

app/views/nivel_academicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nivelacdemico:</strong>
  <%= @nivel_academico.nivelAcdemico %>
</p>

<%= link_to 'Edit', edit_nivel_academico_path(@nivel_academico) %> |
<%= link_to 'Back', nivel_academicos_path %>